# Generated by Django 3.1.7 on 2022-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Class', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('grno', models.IntegerField(max_length=30)),
                ('birth', models.DateField(max_length=30)),
                ('address', models.TextField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=10)),
            ],
        ),
    ]
