# Generated by Django 3.1.7 on 2022-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grno',
            field=models.IntegerField(),
        ),
    ]
